# Site settings
title: codeforpb
email: ljan@mail.upb.de
description: "Hier werden demnächst Infos über das OK Lab Paderborn zu finden sein."
baseurl: ""
url: "http://codeforpb.de"

# Build settings
markdown: kramdown
permalink: pretty
