# Site settings
title: codeforpb
email: ljan@mail.upb.de
description: "Die Infoseite des zukünftigen OK Lab Paderborn"
baseurl: ""
url: "http://codeforpb.de"
username: codeforpb


# Build settings
markdown: kramdown
permalink: pretty
